# Form implementation generated from reading ui file 'StartWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
# Command for creation executable .py -file: pyuic6 -x guifile.ui -o guifile.py


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from MainMenu import Ui_MainWindow


class Ui_Start(object):
        
    def setupUi(self, Start):
        Start.setObjectName("Start")
        Start.resize(769, 497)
        Start.setMouseTracking(True)
        Start.setTabletTracking(True)
        Start.setAutoFillBackground(True)
        Start.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Start)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setTabletTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.startMainWindow)
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        Start.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Start)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 21))
        self.menubar.setObjectName("menubar")
        Start.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Start)
        self.statusbar.setObjectName("statusbar")
        Start.setStatusBar(self.statusbar)

        self.retranslateUi(Start)
        QtCore.QMetaObject.connectSlotsByName(Start)

    def retranslateUi(self, Start):
        _translate = QtCore.QCoreApplication.translate
        Start.setWindowTitle(_translate("Start", "MainWindow"))
        self.label.setText(_translate("Start", "IC-Autodocker"))
        self.pushButton.setText(_translate("Start", "Start"))
        self.pushButton_2.setText(_translate("Start", "Anleitungen"))
        self.pushButton_3.setText(_translate("Start", "Beenden"))
        
    def setButtonCommands(self):
        pass
    
    def startMainWindow(self):
        self.MainWindowWindow = QtWidgets.QMainWindow(Start)
        self.MainWindowUI = Ui_MainWindow()
        self.MainWindowUI.setupUi(self.MainWindowWindow)
        self.MainWindowWindow.show()
        Start.hide()
        


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Start = QtWidgets.QMainWindow()
    ui = Ui_Start()
    ui.setupUi(Start)
    Start.show()
    ui.setButtonCommands()
    sys.exit(app.exec())
